### ISSUE TITLE
v0.3.3 Breaks current state nodes

### ISSUE THREAD

**Issue by PrimusNZ** [Spartan-II-117/node-red-contrib-home-assistant#18]
**Describe the bug**
Since v0.3.3 all nodes querying the state of a home assistant entity returns a full object with Override Payload enabled - When disabled, the payload is a timestamp

For Example, sensor.indoor_temp used to return `24.2` as the payload, now returns
```
{"entity_id":"sensor.indoor_temp","state":"24.2","attributes":{"unit_of_measurement":"°C","friendly_name":"Indoor Temperature","icon":"mdi:thermometer"},"last_changed":"2018-07-18T10:15:12.587385+00:00","last_updated":"2018-07-18T10:15:12.587385+00:00"}
```
Turning off Override Payload returns `1531908922336` as the payload

This breaks all flows that expected the previous behaviuor of just returning the state

**To Reproduce**
1. Place a inject node
2. Link inject node to current state node calling home assistant sensor object
3. Link current state node to debug
4. trigger inject node

**Expected behavior**
I expected the payload to be just `24.2` with Override Payload enabled, not an entire json object

**Screenshots**
Override Payload Enabled
![screenshot_20180718_215232](https://user-images.githubusercontent.com/330174/42875589-48b5e614-8ad8-11e8-903d-03745e359d8b.png)

Override Payload Disabled
![screenshot_20180718_222534](https://user-images.githubusercontent.com/330174/42876042-8a01c36c-8ad9-11e8-84f0-494ab3aa162c.png)

**Example Flow**
```
[{"id":"276b4df5.371122","type":"ui_gauge","z":"6c123bf4.03dab4","name":"","group":"4c5a3645.049a28","order":0,"width":0,"height":0,"gtype":"gage","title":"Temp","label":"°C","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":850,"y":120,"wires":[]},{"id":"16d2b1a9.30868e","type":"ui_gauge","z":"6c123bf4.03dab4","name":"","group":"4c5a3645.049a28","order":0,"width":0,"height":0,"gtype":"gage","title":"Humidity","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":860,"y":160,"wires":[]},{"id":"4b03e491.4f623c","type":"inject","z":"6c123bf4.03dab4","name":"","topic":"","payload":"","payloadType":"date","repeat":"60","crontab":"","once":true,"onceDelay":"5","x":490,"y":180,"wires":[["6adf3b3c.04b464","5986fb9f.b31894","9e0a5af6.a74c28","7b722ba9.6edc34"]]},{"id":"6adf3b3c.04b464","type":"api-current-state","z":"6c123bf4.03dab4","name":"Indoor Temp","server":"12a9b42c.ce1dbc","halt_if":"","override_payload":false,"entity_id":"sensor.indoor_temp","propertyType":"msg","property":"payload","x":670,"y":120,"wires":[["276b4df5.371122"]]},{"id":"5986fb9f.b31894","type":"api-current-state","z":"6c123bf4.03dab4","name":"Indoor Humidity","server":"12a9b42c.ce1dbc","halt_if":"","override_payload":true,"entity_id":"sensor.indoor_humidity","propertyType":"msg","property":"payload","x":680,"y":160,"wires":[["16d2b1a9.30868e"]]},{"id":"fff210bd.3e9fe","type":"ui_gauge","z":"6c123bf4.03dab4","name":"","group":"1e521c4c.358d84","order":0,"width":0,"height":0,"gtype":"gage","title":"Temp","label":"°C","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":850,"y":200,"wires":[]},{"id":"9e0a5af6.a74c28","type":"api-current-state","z":"6c123bf4.03dab4","name":"Outdoor Temp","server":"12a9b42c.ce1dbc","halt_if":"","override_payload":true,"entity_id":"sensor.pws_temp_c","propertyType":"msg","property":"payload","x":680,"y":200,"wires":[["fff210bd.3e9fe"]]},{"id":"1ae676cb.d023a9","type":"ui_gauge","z":"6c123bf4.03dab4","name":"","group":"1e521c4c.358d84","order":0,"width":0,"height":0,"gtype":"gage","title":"Humidity","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":860,"y":240,"wires":[]},{"id":"7b722ba9.6edc34","type":"api-current-state","z":"6c123bf4.03dab4","name":"Outdoor Humidity","server":"12a9b42c.ce1dbc","halt_if":"","override_payload":true,"entity_id":"sensor.pws_relative_humidity","propertyType":"msg","property":"payload","x":690,"y":240,"wires":[["1ae676cb.d023a9"]]},{"id":"4c5a3645.049a28","type":"ui_group","z":"","name":"Indoor","tab":"d6da9d1b.d82ff","order":1,"disp":true,"width":"6","collapse":false},{"id":"12a9b42c.ce1dbc","type":"server","z":"","name":"Home Assistant","url":"https://automation.ryandavies.co.nz","pass":"94LTDTheBeast"},{"id":"1e521c4c.358d84","type":"ui_group","z":"","name":"Outdoor","tab":"d6da9d1b.d82ff","order":2,"disp":true,"width":"6","collapse":false},{"id":"d6da9d1b.d82ff","type":"ui_tab","z":"","name":"Climate","icon":"dashboard","order":1}]
```

**Environment (please complete the following information):**
 - Node Red Version: v0.18.7
 - NR Home Assistant Plugin Version: 0.3.3
 - Is Node Red running in Docker: Yes

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: Yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): I cannot with the internet resources I have

**Additional context**
Running Hass.io on HassOS

**Comment by oskretc** [comment]
I have the same issue. Fix it using payload.state to get the temperature.

It is nice to have the extra info. but once decided needs to stay that way.

**Comment by PrimusNZ** [comment]
You've completely missed the point of this issue.
This line https://github.com/Spartan-II-117/node-red-contrib-home-assistant/blob/8303c9def919e7254d158a72260d8263977bc6e8/nodes/api_current-state/api_current-state.js#L57 suggests that having that option ticked will operate as it did in 0.3.2 for backwards compatibility which it is not
https://github.com/Spartan-II-117/node-red-contrib-home-assistant/pull/17/files#diff-a5b859b48ef107b7db426bed06173c9c

**Comment by oskretc** [comment]
I agree. I had not followed the development and was not aware of that functionality.

**Comment by Spartan-II-117** [comment]
if you have a PR to fix this i'd welcome it, as i'm not really a programmer, but I'll see what i can do

**Comment by Spartan-II-117** [comment]
I think there needs to be a discussion on what this node SHOULD do, rather than just what it used to do. 
option 1: preserve the topic id from the incoming message, nut replace the payload with the status of the  checked device?
option 2: replace the topic, object, and payload with those of the entity being checked
option 3: something else?

it seems odd to me to replace just the payload, because then you have a message coming in with the name of one entity, and the state of another

**Comment by Spartan-II-117** [comment]
Please check if the code in dev-master solves your problem

**Comment by PrimusNZ** [comment]
I'll give it a whirl and let you know

**Comment by PrimusNZ** [comment]
Created PR https://github.com/Spartan-II-117/node-red-contrib-home-assistant/pull/19 with some workarounds (Code mostly correct from what I saw)

**Comment by Spartan-II-117** [comment]
I created PR #20 with a simplification that should restore complete compatibility with upstream

**Comment by drjared88** [comment]
The point of the disabling the override payload option is to ignore the payload of the current node and just pass through the current payload. In your example when you get a result of that number, that is the timestamp from the inject node.

**Comment by drjared88** [comment]
Here is my example of where I would disable the override payload. In this flow I have it disabled on the 'Family Gone' node so that it passes through the payload of the door lock so I can then send a message using it's friendly name like "The front door lock is unlocked".
![payload](https://user-images.githubusercontent.com/24482841/42958385-a0d05eaa-8b42-11e8-9ae3-2aae22170432.JPG)

**Comment by drjared88** [comment]
As for it not being the same out put as 0.3.2 with it checked. It is. This fork handled the payload this way before my PR which is different then how the master branch handles it. Right or wrong is debatable but I continued the way it is as to not break peoples current flows.

That being said, if you are migrated from the master branch then you will have to update flows from msg.payload to msg.payload.state.

**Comment by Spartan-II-117** [comment]
@drjared88 I disagree, I understand that that was the way it was previously in this branch, but i strongly feel that the payload should be a string, the object should be the state object to match the behavior of state-changed node

**Comment by drjared88** [comment]
@Spartan-II-117 I was not saying I supported the way it was. I am just saying that was my reason for keeping it that way. I have tested your current PR and I like it that way which aligns with the master branch. It does break existing flows now though.

**Comment by Spartan-II-117** [comment]
unfortunately yes, but fixing it now will prevent lots more people (if they ever switch to this fork) from having to make changes.

**Comment by PrimusNZ** [comment]
The majority of the HassIO / Home assistant community have already switched to this fork because of changes in the node red addon which now uses this fork.

Also, Removing
```
            if (this.nodeConfig.propertyType == 'flow') {
                this.context().flow.set(this.nodeConfig.property, currentState);
            } else if (this.nodeConfig.propertyType == 'global') {
                this.context().global.set(this.nodeConfig.property, currentState);
            } else {
```
You have now removed storing the response from the current state in the flow context or the global context - Which is another major breaking change.

**Comment by Spartan-II-117** [comment]
I decided to give up on the point about how i think it should work (passing nothing through unless a box is checked) and make it match the upstream exactly, the other functions you mentioned can be accomplished with change nodes externally if desired

> unmodified with of exception, it put the current state object into a msg.data property
which replaces the msg.data put there by the api-state-changed node. if we want to make changes away from the old way lets make a n issue for each change that should be made and get some discussion going to determine the right course of action. 

I heard a bunch of cpeople were unhappy about it not matching upstream, so i made it match upstream.it now matches upstream so i am closing this issue.

**Comment by Spartan-II-117** [comment]
> The majority of the HassIO / Home assistant community have already switched to this fork because of changes in the node red addon which now uses this fork.

The addon no longer uses this fork, due to the breaking of compatibility with upstream.
