### ISSUE TITLE
Current state nodes "drop off"

### ISSUE THREAD

**Issue by chimpy** [Spartan-II-117/node-red-contrib-home-assistant#27]
Hi!

Not quite sure how to describe this bug. After a few days of running with no problems, current state nodes will all "drop off" and no longer check their states.

That is, any Halt conditions are ignored and my lights start turning on from motion cues in the middle of the day even though an Evening Mode boolean normally stops that from happening.

Status icons also disappear. Restarting node-red does nothing. I am only able to restore full functionality by rm'ing the node-module folder and doing another git clone of the repo.

Has anyone else experienced remotely the same thing? Other than that I love this fork.

**Comment by Spartan-II-117** [comment]
I haven't, I run my nodeRed instance for weeks at a time and have never experienced this issue, could you make a copy of your node_modules folder right after you clone the repo, then run a diff between that and the installed version once the problem arises?

**Comment by chimpy** [comment]
That’s a great idea! Will do.

**Comment by Spartan-II-117** [comment]
Thanks! let me know what you find!

**Comment by chimpy** [comment]
Ok so this was all down to my botched way of installing your fork over the original. I shouldn't have just rm'd the folder and git cloned yours. If you do that npm thinks that you're still using the official repository and will "update" and overwrite this fork with the old one. As a form of atonement, here is how to do it properly and cleanly and how to recover from my bad way:
(package-lock.json gets regenerated after we `npm install`)
(you could also probably just `npm uninstall node-red-contrib-home-assistant` but I didn't want to risk anything not working)

`sudo service nodered stop`
`cp -R ~/.node-red a_backup_folder`
`rm -rf ~/.node-red/node_modules/node-red-contrib-home-assistant`
`rm ~/.node-red/package-lock.json`
`sed -i.bak '/node-red-contrib-home-assistant/d' ~/.node-red/package.json`
`cd /somewhere`
`git clone https://github.com/Spartan-II-117/node-red-contrib-home-assistant.git`
`cd ~/.node-red`
`npm install /somewhere/node-red-contrib-home-assistant`
`sudo service nodered start`
