### ISSUE TITLE
current state entity_id field should be optional

### ISSUE THREAD

**Issue by FezVrasta** [Spartan-II-117/node-red-contrib-home-assistant#30]
**Describe the bug**
The `current_state` node doesn't accept an empty `payload.entity_id` but it actually supports it.

If I don't specify one (to have it read the value from the existing `msg.payload.entity_id`) whenever I deploy the flow it will warn me about the missing property definition.

Ideally the entity_id field should be marked as optional.

**Comment by Spartan-II-117** [comment]
can you put in a pull request for this?

**Comment by FezVrasta** [comment]
I never worked with the Node-RED internals, I read there is a `required` boolean that should be set to `true` to enforce the current behavior but I couldn't find it :-(

**Comment by Spartan-II-117** [comment]
take a look at nodes/api-current-state/api-current-state.html and see if changing the file there fixes your issue, then submit a PR

**Comment by FezVrasta** [comment]
Oh right, I thought html was just for visualization. Great!

**Comment by Spartan-II-117** [comment]
did you test the change?

**Comment by FezVrasta** [comment]
Yes, it doesn't warn me anymore if I leave the field empty.

**Comment by Spartan-II-117** [comment]
fixed in 0.3.7

**Comment by chimpy** [comment]
Is this extra functionality detailed in the current state node instructions? If not it might be prudent to add it in :)

**Comment by FezVrasta** [comment]
The functionality has always been there. But the input validation prevented to take advantage of it in a clean way
